### ISSUE TITLE
Failing to parse method with more than 17 characters

### ISSUE THREAD

**Issue by gearoidc** [phpDocumentor/ReflectionDocBlock#164] opened 2019-04-18 17:11 UTC
@method line fails to come back from parseTagBlock in DocBlockFactory
```
/**
  * togglecheckboxitem
  *
  * Toggle checkbox item
  * @method togglecheckboxitem
  */
 ```

However this doc block works (minus the **m** at the end of the method name)
```
/**
  * togglecheckboxitem
  *
  * Toggle checkbox item
  * @method togglecheckboxite
  */
 ```

Im still debugging what comes from the call below
```
//DocBlockFactory:231
$result[$key] = $this->tagFactory->create(trim($tagLine), $context);
```
as the $tagLine goes in but **null** is returned. If you have any ideas in the mean time that would be great. I am using the latest release.

Thanks

**Comment by filecage** [comment] 2019-04-29 17:01
Your provided example works for me with the current master version as well as with the `4.3.0` release. Can you provide a more detailed information on your setup and maybe a piece of code that allows reproduction of the issue?

**Comment by gearoidc** [comment] 2019-04-30 09:15
Yes I'll get some code together for you. Thanks for replying @filecage

**Comment by jaapio** [comment] 2020-02-09 08:54
Hi @gearoidc,
Is this still any issue for you or did you find where it went wrong?

**Comment by gearoidc** [comment] 2020-02-09 11:26
Thanks for checking in to be honest I have not had a chance to finish the chunk of code I was working on as I was moved to another piece of functionality. I will hope to get back to this in a few weeks and I will let you know. Thanks for the post.
gearoid

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=10.0.32&pv=10.15.3&source=email_footer_2]
On Sun, Feb 9, 2020 at 8:54, Jaap van Otterdijk <notifications@github.com> wrote:
Hi @gearoidc [https://github.com/gearoidc] ,
Is this still any issue for you or did you find where it went wrong?

**Comment by jaapio** [comment] 2020-02-12 20:16
Issue should have been fixed in master. We will release a new version soon

**Closed by jaapio** 2020-02-12 20:16 UTC
